
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="StyleSheet" type="text/css" href="{$basePath}/public/css/frontend/screen.css" />
	<script type="text/javascript" src="{$basePath}/public/libs/jquery/jquery.js"></script>
	<script type="text/javascript" src="{$basePath}/public/libs/jquery/jquery.livequery.js"></script>
	<script type="text/javascript" src="{$basePath}/public/libs/NetteAjax/jquery.nette.js"></script>
	<script type="text/javascript" src="{$basePath}/public/js/hideControl.js"></script>
</head>

<body>

<div id="content">
@{include #content}
</div>
</body>
</html>

